improved configure and build process

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,34 +1,39 @@
 #!/bin/sh
 #********************************************************************************
-# check for existing qmail installation
-[ ! -f `head -1 conf-home`/bin/qmail-smtpd ] && \
-  echo "Couldn't find an installation! Check 'conf-home'! Aborting!" && exit
+@make clean 2>/dev/null
 
+# check for existing qmail installation
+[ -f conf-build ] && . ./conf-build
+[ -f ../find-qmaildir ] && . ../find-qmaildir || echo "$QMAILDIR" > conf-home
+
+[ ! -f `head -1 conf-home`/bin/qmail-smtpd ] && \
+  echo "Couldn't find valid *qmail installation, check 'conf-build'!" && exit 1
+# check qlibs directory
+[ -f conf-build ] && . ./conf-build
+[ "$QLIBDIR" ] && echo "$QLIBDIR" > conf-qlibs
 #********************************************************************************
-make clean 2>/dev/null
 cp Makefile.in Makefile.in.tmp
 
-OS=`uname`
+OS=`uname -s | tr 'A-Z' 'a-z'`
 echo "Checking system ... "${OS}" found!"
-if [ $OS ] && [ $OS == "Linux" ] ; then
-#if [ `uname` == "Linux" ] ; then
+if [ $OS ] && [ $OS == "linux" ] ; then
   echo "Add -lresolv to linker flags ... done!"
   sed s}'LFLAGS ='}'LFLAGS =-lresolv'}g Makefile.in.tmp > Makefile.tmp
-  mv Makefile.tmp Makefile.in.tmp
 fi
 
+mv Makefile.tmp Makefile.in.tmp
 VERS="VERSION="`head -1 VERSION.lib`
-echo "Set version string ... "`head -1 VERSION`
+echo "Set library version string ... "`head -1 VERSION.lib`
 sed s}^VERSION.*$}$VERS}g Makefile.in.tmp > Makefile.tmp
+
+mv Makefile.tmp Makefile.in.tmp
+sed s}QLIBDIR}`head -1 conf-qlibs`}g Makefile.in.tmp > Makefile.tmp
 
 mv Makefile.tmp Makefile
 rm Makefile.in.tmp
 
-
 #********************************************************************************
-# Check for external tools
-
-# check for system tools (required) !!!
+# check for system tools (required)
 for f in bash hostname [ test make perl awk fmt unix2dos fixcrio
 do
   echo -n "Checking for $f ... "
@@ -36,20 +41,5 @@ do
   if [ $? -ne 0 ] ; then echo "not found!" ; exit 1 ; fi
 done
 
-
-
-
-#n=`find /usr/local/*/bin -name qmail-smtpd -type f -print > instdir.tmp`
-
-#n=`find /usr/local/*/bin -name qmail-smtpd -type f -print | wc -l`
-n=`find /{usr/local,var}/* -name qmail-smtpd -type f -print | xargs dirname | xargs dirname | tee instdir.tmp |  wc -l`
-if [ $n -gt 1 ] ; then
-  echo "Found multiple possible installations:"
-#  cat instdir.tmp
-fi
-if [ $n = 1 ] ; then cat instdir.tmp ; fi
-#QMAILDIR=`head -1 conf-home`
-
-#mkdir -p QMAILDIR/etc/dkimkeys
 
 echo "Done! Now run make."
